apiVersion: apps/v1
kind: Deployment
metadata:
  name: diabetes-risk-model-deployment
  labels:
    app: diabetes-risk-model
    app.kubernetes.io/name: diabetes-risk-model-deployment
    app.kubernetes.io/version: "0.1.0"
    app.kubernetes.io/component: model-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: diabetes-risk-model
  template:
    metadata:
      labels:
        app: diabetes-risk-model
    spec:
      containers:
        - name: diabetes-risk-model
          image: diabetes_risk_model_service:0.1.0
          ports:
          - containerPort: 80
            protocol: TCP
          imagePullPolicy: Never
          livenessProbe:
            httpGet:
              scheme: HTTP
              path: /api/health
              port: 8000
            initialDelaySeconds: 0
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 5
            successThreshold: 1
          readinessProbe:
            httpGet:
              scheme: HTTP
              path: /api/health/ready
              port: 8000
            initialDelaySeconds: 0
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 5
            successThreshold: 1
          startupProbe:
            httpGet:
              scheme: HTTP
              path: /api/health/startup
              port: 8000
            initialDelaySeconds: 0
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 5
            successThreshold: 1
          resources:
            requests:
              cpu: "100m"
              memory: "250Mi"
            limits:
              cpu: "200m"
              memory: "250Mi"
          env:
            - name: REST_CONFIG
              value: ./configuration/kubernetes_rest_config.yaml
            - name: MINIO_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: diabetes-risk-model-service-secrets
                  key: minio-access-key
            - name: MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: diabetes-risk-model-service-secrets
                  key: minio-secret-key
            - name: PARAMETERS_SIGNING_KEY
              valueFrom:
                secretKeyRef:
                  name: diabetes-risk-model-service-secrets
                  key: parameters-signing-key
          volumeMounts:
            - name: config-volume
              mountPath: /service/configuration
      volumes:
        - name: config-volume
          configMap:
            name: model-service-configuration
            items:
              - key: kubernetes_rest_config.yaml
                path: kubernetes_rest_config.yaml
---
apiVersion: v1
kind: Service
metadata:
  name: diabetes-risk-model-service
  labels:
    app.kubernetes.io/name: diabetes-risk-model-service
    app.kubernetes.io/version: "0.1.0"
    app.kubernetes.io/component: model-service
spec:
  type: NodePort
  selector:
    app: diabetes-risk-model
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8000